spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dormitory_management?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ho?c 'validate', 'create', 'create-drop' tùy vào m?c ?ích s? d?ng
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect  # ho?c MySQL5Dialect n?u b?n dùng MySQL 5

server:
  port: 8082  # C?ng mà ?ng d?ng Spring Boot s? ch?y, có th? thay ??i n?u c?n
